name: Generate Pacman Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:    # Allows you to run it manually
  push:
    branches: [ main ]

jobs:
  generate:
    permissions: contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman SVGs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
